/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Donor;

import Configuration.EcoSystem;
import Donation.Employee.Employee;
import Donation.Enterprise.Enterprise;
import Donation.Network.Network;
import Donation.Organization.Organization;
import static Donation.Organization.Organization.orgType.DonorIndividualOrg;
import Donation.Role.DonorRole;
import Donation.UserAccount.UserAccount;
import Donation.WorkQueue.DonorRegistrationWorkRequest;
import Donation.WorkQueue.WorkQueue;
import Donation.WorkQueue.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raushan
 */
public class DonorAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorAdminJPanel
     */
     private static JPanel jPanel;
    private static UserAccount userAccount;
    private static EcoSystem ecosystem;
    private static Network network;
    private static Enterprise enterprise;
    public DonorAdminJPanel(EcoSystem ecosystem, Network network, Enterprise enterprise, JPanel jPanel, UserAccount userAccount) {
        initComponents();
        this.ecosystem = ecosystem;
        this.network = network;
        this.enterprise = enterprise;
        this.jPanel = jPanel;
        this.userAccount = userAccount;
        populateTable();
        populateTableOrg();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrg = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtOrgName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAddOrganization = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRequestDonor = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 54, 57));

        jTabbedPane1.setBackground(new java.awt.Color(220, 215, 201));
        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 215, 201), 1, true));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(44, 54, 57));
        jPanel1.setLayout(null);

        jScrollPane1.setForeground(new java.awt.Color(2, 55, 108));

        tableOrg.setBackground(new java.awt.Color(220, 215, 224));
        tableOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOrg);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 60, 770, 120);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 215, 201));
        jLabel1.setText("Organization:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 152, 22);

        txtOrgName.setBackground(new java.awt.Color(220, 215, 224));
        txtOrgName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtOrgName);
        txtOrgName.setBounds(420, 290, 220, 40);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 215, 201));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 300, 50, 22);

        btnAddOrganization.setBackground(new java.awt.Color(220, 215, 201));
        btnAddOrganization.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnAddOrganization.setText("Add");
        btnAddOrganization.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrganizationActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddOrganization);
        btnAddOrganization.setBounds(540, 360, 100, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(220, 215, 201));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Create Doner Organization");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 220, 330, 29);

        jTabbedPane1.addTab("Organization", jPanel1);

        jPanel2.setBackground(new java.awt.Color(44, 54, 57));
        jPanel2.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(220, 215, 224));
        jScrollPane2.setBorder(null);

        tableRequestDonor.setBackground(new java.awt.Color(220, 215, 224));
        tableRequestDonor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request #", "Request Date", "Requestor Name", "Organization Type", "Address", "Contact", "Email Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableRequestDonor);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 810, 140);

        btnProcess.setBackground(new java.awt.Color(220, 215, 201));
        btnProcess.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        jPanel2.add(btnProcess);
        btnProcess.setBounds(370, 280, 110, 40);

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 215, 201));
        jLabel4.setText("Donor Requests:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 20, 150, 22);

        jTabbedPane1.addTab("New Requests ", jPanel2);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(220, 215, 201));
        jLabel5.setText("Welcome Donor Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableRequestDonor.getSelectedRow();

        if (selectedRow >= 0) {
            DonorRegistrationWorkRequest wreq = (DonorRegistrationWorkRequest) tableRequestDonor.getValueAt(selectedRow, 0);
            if (wreq.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Donor processed already!");
                return;
            }
            else {
                wreq.setReceiver(userAccount);
                wreq.setStatus("Pending");
                if (wreq.getOrgType() == Organization.orgType.DonorIndividualOrg) {
                    System.out.println(enterprise.getOrgDirectory().getOrgList());
                    for(Organization org : enterprise.getOrgDirectory().getOrgList()){
                        System.out.print(enterprise.getOrgDirectory());
                        System.out.print(Organization.orgType.DonorIndividualOrg);
                        if(org.getOrgType() == Organization.orgType.DonorIndividualOrg){
                            Employee emp = org.getEmpDirectory().addEmployee(wreq.getName());
                            System.out.print(emp.getName());
                            UserAccount ua = org.getuserAccountList().addUserAccount(wreq.getUserName(), wreq.getUserPassword(), new DonorRole(), emp);
                            System.out.print(ua);
                        }
                    }
                }
                String email = tableRequestDonor.getValueAt(selectedRow, 6).toString();
                String name =  tableRequestDonor.getValueAt(selectedRow, 2).toString();
                wreq.setStatus("Completed");
                sendEmail(email,name);
                JOptionPane.showMessageDialog(null, "Donor account created.");
                populateTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to process.");
            return;
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnAddOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrganizationActionPerformed
        // TODO add your handling code here:
        String orgName = txtOrgName.getText().trim();
        Organization.orgType type = DonorIndividualOrg;
        if(!orgName.isEmpty()){
            Organization o = enterprise.getOrgDirectory().addOrganization(type, txtOrgName.getText());
            JOptionPane.showMessageDialog(null, "Organization created.");
            txtOrgName.setText("");

        } else{
            JOptionPane.showMessageDialog(null, "Please enter Organization name", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        populateTableOrg();
    }//GEN-LAST:event_btnAddOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrganization;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableOrg;
    private javax.swing.JTable tableRequestDonor;
    private javax.swing.JTextField txtOrgName;
    // End of variables declaration//GEN-END:variables


    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tableRequestDonor.getModel();
        model.setRowCount(0);

        if (enterprise.getWorkQueue() == null) {
            enterprise.setWorkQueue(new WorkQueue());
        }
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        
        for (WorkRequest workRequest : enterprise.getWorkQueue().getWorkReqList()) {
            if (workRequest instanceof DonorRegistrationWorkRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = workRequest;
                row[1] = formatter.format(((DonorRegistrationWorkRequest) workRequest).getRequestDateTime());
                row[2] = ((DonorRegistrationWorkRequest) workRequest).getName();
                row[3] = ((DonorRegistrationWorkRequest) workRequest).getOrgType();
                row[4] = ((DonorRegistrationWorkRequest) workRequest).getUserAddress();
                row[5] = ((DonorRegistrationWorkRequest) workRequest).getUserContact();
                row[6] = ((DonorRegistrationWorkRequest) workRequest).getUserEmailId();
                row[7] = ((DonorRegistrationWorkRequest) workRequest).getStatus();

                model.addRow(row);
            }
        }

    }
    private void populateTableOrg() {
        DefaultTableModel model = (DefaultTableModel) tableOrg.getModel();
        
        model.setRowCount(0);
            for(Organization org : enterprise.getOrgDirectory().getOrgList()){
                Object[] row = new Object[1];
                row[0] = org.getName();
                model.addRow(row);
            }   
    }
    
    private void sendEmail(String email, String name) {
        String to = email;
        String from = "donar2022neu@gmail.com";
        String message = "Hi " + name + ", Your account has been created successfully with your username and password provided. Please login and show your interest in donating funds/kits.";
        String subject = "Account : Created";

        String host = "smtp.gmail.com";

        Properties properties = System.getProperties();
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.ssl.enable", "true");
        properties.put("mail.smtp.auth", "true");

        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("donar2022neu@gmail.com", "lwrplcpuyfwzdfvz");
            }

        });

        //session.setDebug(true);
        MimeMessage mail = new MimeMessage(session);
        try {

            mail.setFrom(from);
            mail.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            mail.setSubject(subject);
            mail.setText(message);
            Transport.send(mail);
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}
