/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Configuration.EcoSystem;
import Donation.DB4OUtil;
import Donation.Enterprise.Enterprise;
import Donation.Network.Network;
import Donation.Organization.Organization;
import Donation.Role.DisasterReliefKitSupplyManagerRole;
import Donation.Role.DisasterReliefOrgAdminRole;
import Donation.Role.DonationAdminRole;
import Donation.Role.DonorAdminRole;
import Donation.Role.DonorRole;
import Donation.Role.EducationDonationOrgAdminRole;
import Donation.Role.EducationKitSupplyManagerRole;
import Donation.Role.FundsAdminRole;
import Donation.Role.FundsOrgAdminRole;
import Donation.Role.KitSupplyAdmin;
import static Donation.Role.Role.RoleType.DisasterReliefOrgAdminRole;
import static Donation.Role.Role.RoleType.EducationDonationOrgAdminRole;
import Donation.Role.SystemAdminRole;
import Donation.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.DisasterRelief.DisasterReliefOrgJPanel;
import ui.DisasterRelief.DisaterReliefKitSupplyManagerJPanel;
import ui.Donation.DonationAdminJPanel;
import ui.Donor.DonorAdminJPanel;
import ui.Donor.DonorJPanel;
import ui.Donor.RegistrationDonorJPanel;
import ui.Education.EducationDonationOrgJPanel;
import ui.Education.EducationKitSupplyManagerJPanel;
import ui.Funds.FundsAdminJPanel;
import ui.Funds.FundsManagerJPanel;
import ui.KitSupply.KitSupplyAdminJPanel;
import ui.System.SystemAdminPanel;

/**
 *
 * @author Raushan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem ecosystem;
    UserAccount userAccount;
    Network network;
    Enterprise enterprise;
    Organization organization;
    public MainJFrame() {
        initComponents();
        ecosystem = dB4OUtil.retrieveSystem();
        EcoSystem.setInstance(ecosystem);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnRegisterDoner = new javax.swing.JButton();
        txtUserPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(63, 78, 79));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 247, 247));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 247, 247));
        jLabel2.setText("Password");

        txtUserName.setBackground(new java.awt.Color(220, 215, 224));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(220, 215, 201));
        jButton1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(220, 215, 201));
        btnLogout.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnRegisterDoner.setBackground(new java.awt.Color(220, 215, 201));
        btnRegisterDoner.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnRegisterDoner.setText("Donor Registration");
        btnRegisterDoner.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterDoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDonerActionPerformed(evt);
            }
        });

        txtUserPassword.setBackground(new java.awt.Color(220, 215, 224));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUserPassword)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnRegisterDoner, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRegisterDoner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(44, 54, 57));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 62)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 215, 201));
        jLabel3.setText("Donation Management System");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel3)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGap(61, 61, 61))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String userName = txtUserName.getText();
        String userPassword = new String(txtUserPassword.getPassword());

        userAccount = ecosystem.getuserAccountList().authenticateUser(userName, userPassword);
        network = null;
        enterprise = null;
        organization = null;

        if (userAccount == null) {
            for (Network n : ecosystem.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEntList()) {
                    userAccount = e.getuserAccountList().authenticateUser(userName, userPassword);
                    network = n;
                    if (userAccount == null) {
                        for (Organization org : e.getOrgDirectory().getOrgList()) {
                            userAccount = org.getuserAccountList().authenticateUser(userName, userPassword);
                            if (userAccount != null) {
                                network = n;
                                enterprise = e;
                                organization = org;
                                break;
                            }
                        }

                    } else {
                        enterprise = e;
                        break;
                    }
                    if (organization != null) {
                        break;
                    }
                }
                if (enterprise != null) {
                    break;
                }
            }
        }
        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Credentials");
            return;
        } else {
            txtUserName.setEnabled(false);
            txtUserPassword.setEnabled(false);
            btnLogout.setEnabled(true);
            jButton1.setEnabled(false);
            btnRegisterDoner.setEnabled(false);
            jPanel2.setVisible(true);
            txtUserName.setText("");
            txtUserPassword.setText("");
            changePanel();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        txtUserName.setEnabled(true);
        txtUserPassword.setEnabled(true);
        btnRegisterDoner.setEnabled(true);
        jButton1.setEnabled(true);
        btnLogout.setEnabled(false);
        btnLogout.setText("Logout");
        dB4OUtil.storeSystem(ecosystem);

        txtUserName.setText("");
        txtUserPassword.setText("");

        jSplitPane1.setRightComponent(jPanel2);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRegisterDonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterDonerActionPerformed
        // TODO add your handling code here:
        RegistrationDonorJPanel panel = new RegistrationDonorJPanel(jPanel2, ecosystem);
        jSplitPane1.setRightComponent(panel);
        txtUserName.setEnabled(false);
        txtUserPassword.setEnabled(false);
        btnLogout.setEnabled(true);
        jButton1.setEnabled(false);
        btnRegisterDoner.setEnabled(false);
        jPanel2.setVisible(true);
        txtUserName.setText("");
        txtUserPassword.setText("");
    }//GEN-LAST:event_btnRegisterDonerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegisterDoner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables

    private void changePanel() {

        if (userAccount != null && userAccount.getRole() != null) {
            if (userAccount.getRole() instanceof SystemAdminRole) {
                SystemAdminPanel panel = new SystemAdminPanel(jPanel2, ecosystem);
                jSplitPane1.setRightComponent(panel);
            } 
            else if(userAccount.getRole() instanceof DonationAdminRole) {
                DonationAdminJPanel panel = new DonationAdminJPanel(ecosystem, network, enterprise, jPanel2, userAccount);
                jSplitPane1.setRightComponent(panel);
            } 
            else if(userAccount.getRole() instanceof FundsAdminRole) {
                FundsAdminJPanel panel = new FundsAdminJPanel(ecosystem, network, enterprise,jPanel2, userAccount);
                jSplitPane1.setRightComponent(panel);
            } 
            else if(userAccount.getRole() instanceof KitSupplyAdmin) {
                KitSupplyAdminJPanel panel = new KitSupplyAdminJPanel(ecosystem, network, enterprise,jPanel2, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof DonorAdminRole) {
                DonorAdminJPanel panel = new DonorAdminJPanel(ecosystem, network, enterprise,jPanel2, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof DonorRole) {
                DonorJPanel panel = new DonorJPanel(ecosystem, network, enterprise,jPanel2, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof EducationDonationOrgAdminRole) {
                EducationDonationOrgJPanel panel = new EducationDonationOrgJPanel(ecosystem, network,organization, enterprise,jPanel2, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof DisasterReliefOrgAdminRole) {
                DisasterReliefOrgJPanel panel = new DisasterReliefOrgJPanel( userAccount,enterprise,organization,network );
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof DisasterReliefKitSupplyManagerRole) {
                DisaterReliefKitSupplyManagerJPanel panel = new DisaterReliefKitSupplyManagerJPanel( userAccount,enterprise,organization );
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof EducationKitSupplyManagerRole) {
                EducationKitSupplyManagerJPanel panel = new EducationKitSupplyManagerJPanel(ecosystem, network, organization, enterprise, jPanel2, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof FundsOrgAdminRole) {
                FundsManagerJPanel panel = new FundsManagerJPanel(ecosystem, network, enterprise, jPanel2, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
            
        }

    }
}
